### ISSUE TITLE
Watching input pins with onoff

### ISSUE THREAD

**Issue by fivdi** [webofthings/wot-book#1]
The following piece of code is from [here](https://github.com/webofthings/wot-book/blob/master/chapter4-gpios/proximity-onoff.js#L1-L7)

``` js
var Gpio = require('onoff').Gpio,
    sensor = new Gpio(17, 'in');

sensor.watch(function(err, value) {
    if (err) exit(err);
    console.log(value ? 'there is some one!' : 'not anymore!');
});
```

The `watch` callback is probably never called because the Gpio constructors optional `edge` parameter isn't used. The `edge` parameter specifies whether "falling", "rising", or "both" types of edges on the GPIO input pin should trigger interrupts which in turn will result in the `watch` callback being called. See [here](https://github.com/fivdi/onoff/blob/master/onoff.js#L31-L54) for more info.

For example, to detect interrupts on falling edges something like this would be used:

``` js
var Gpio = require('onoff').Gpio,
    sensor = new Gpio(17, 'in', 'falling');

sensor.watch(function(err, value) {
    if (err) exit(err);
    console.log(value ? 'there is some one!' : 'not anymore!');
});
```

**Comment by domguinard** [comment]
Hi Brian, thanks for your report. Actually the sensor we use is a PIR and last time we tried without the edge param (which I didn't notice thanks!) it did work...
I'll give it a try with the additional param and will report here.
Meanwhile, thanks a lot for the onoff lib, we absolutely love it!

**Comment by fivdi** [comment]
The latest version looks good to me. Good luck with the book. Maybe I'll buy a copy :)
