### ISSUE TITLE
Bad path to config folder in proxy.js

### ISSUE THREAD

**Issue by consulthys** [webofthings/wot-book#10]
On lines 8 and 9 of [proxy.js](https://github.com/webofthings/wot-book/blob/master/chapter9-sharing/social-auth/middleware/proxy.js#L8-L9), the path to the private key and certificate files need to be fixed to

```
    key: fs.readFileSync('../config/change_me_privateKey.pem', 'utf8'),
    cert: fs.readFileSync('../config/change_me_caCert.pem', 'utf8'),
```

**Comment by domguinard** [comment]
corrected, cheers!

**Comment by domguinard** [comment]
Actually I just tested it again with "../" and it does not work for me. This bit of the code is loaded within the context of authProxy.js, at the root of the folder so it should need ./ shouldn't it? Or am I missing something? (did you maybe test this on a Windows platform?), reopening for now.

**Comment by consulthys** [comment]
Well, in `proxy.js` there are two references to files in the `config` folder, one with `../` for `acl.json` ([line 3](https://github.com/webofthings/wot-book/blob/master/chapter9-sharing/social-auth/middleware/proxy.js#L3)) and another with `./` for the key and certificate. So one or the other is wrong, but since this code is executed in the context of `proxy.js`, the right way should be with `../`.

**Comment by domguinard** [comment]
Hi, it does not work for us with `../` for the key and certificate. But is does work with `../` for `acl.json` and `./` for the key and certificate.
The context of `require` is `proxy.js` but the context of loading the certificate is `authProxy.js` as `proxy.js` is required by this module? Getting confused...
