### ISSUE TITLE
Replace deprecated req.param() call

### ISSUE THREAD

**Issue by consulthys** [webofthings/wot-book#11]
On line 9 of [auth.js](https://github.com/webofthings/wot-book/blob/master/chapter9-sharing/social-auth/middleware/auth.js#L9), `req.param('token')` should be `req.params.token` as the former is deprecated.

**Comment by domguinard** [comment]
corrected, cheers!

**Comment by domguinard** [comment]
actually we replaced it by req.query.token as we want the query parameter "token" and req.param('token') also loads it from the query params while req.params.token only looks in the path (see http://expressjs.com/en/api.html#req.param).
