### ISSUE TITLE
Your Test Device is Down

### ISSUE THREAD

**Issue by jasonzoladz** [webofthings/wot-book#18]
http://devices.webofthings.io does not work.  Please fix.

**Comment by domguinard** [comment]
Sorry about that, we switched the network in our office and oversaw this would have an impact. We are fixing it now.

**Comment by jasonzoladz** [comment]
Great.  Thanks!

**Comment by jasonzoladz** [comment]
Just saw that it's up.  Thanks for the quick fix!
