### ISSUE TITLE
Typos and fixes to sensors.js in chapter7

### ISSUE THREAD

**Issue by consulthys** [webofthings/wot-book#2]
In the source code for chapter 7, there are some typos to remove and fixes to be made:
- [Line 56](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part1-2-direct-gateway/routes/sensors.js#L56) should be labelled `#E` instead of `#D`
- [Line 57](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part1-2-direct-gateway/routes/sensors.js#L57) should be removed entirely

**Comment by domguinard** [comment]
Fixed, thanks for that!
