### ISSUE TITLE
Chapter 7-can't control  led  by toggle button

### ISSUE THREAD

**Issue by zixzixzix** [webofthings/wot-book#25]
I can change the status value by postman.
But it not worked when i use plug.html.
I can get the html response and I can see the Action on  the dashboard of EVRYTHING.
but plug-with-control.js has not receive any message

**Comment by domguinard** [comment]
Sorry we missed your message. Do you still have the problem? Which browser are you trying this with?

**Comment by domguinard** [comment]
Fixed with https://github.com/webofthings/wot-book/commit/70d419a2057135c8392998e26e2e89985dd44db7
This error was due to a new security restriction on the EVRYTHNG platform. Thanks for submitting!
