### ISSUE TITLE
Error after running wot-server.js

### ISSUE THREAD

**Issue by logivity** [webofthings/wot-book#26]
I am new to javascripct coding, so pardon me if this is a stupid issue because of lack of my knowledge. Every-time I run Wot-server.js with sudo su user (as sudo node doesn't work with nvm) I get an timeout error as following. Could you please see why this error is happening and how it can be resolved.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: No reply in 247s
    at null._onTimeout (/home/pi/wot-pi/node_modules/coap/lib/retry_send.js:70:16)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by domguinard** [comment]
Hi logivity, sorry we missed your message :/ Do you still have this problem? Which chapter are you trying to run the examples from?

**Comment by KarolPWr** [comment]
I'm having the same problem on my setup - RPi Zero W, only change I made was delete plugin and lines associated with LED control. This occurred by running simple wot server from chapter 7. 

Edit: I 'fixed' the error by catching it - coap still keeps sending error messages that timeout occured, but server is still fully responsive and working (simulated values are changing)
Error: 

```
{ Error: No reply in 247s
    at Timeout._onTimeout (/home/pi/part1-2-direct-gateway/node_modules/coap/lib/retry_send.js:70:16)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5) retransmitTimeout: 247 }
```

**Comment by domguinard** [comment]
Thanks a lot for that report. Which version of Node.js do you use when this happens?

**Comment by KarolPWr** [comment]
Unfortunately I don't remember exactly - I had to re-install the OS because of other issues, but I think it was the newest version of node.js that supported armv6 (for RPi Zero)

**Comment by carloposo** [comment]
Hi there,
I am experiencing the same problem.

Here's my flow:
- cloned git on my Mac
- entered part1-2-direct-gateway folder
- run npm install
- got the attached errors
![screen shot 2018-04-24 at 14 28 18](https://user-images.githubusercontent.com/1691849/39187104-a8041d10-47cc-11e8-8946-8df76f4552ee.png)
![screen shot 2018-04-24 at 14 28 36](https://user-images.githubusercontent.com/1691849/39187105-a8233fd8-47cc-11e8-8878-28caba77dba0.png)
![screen shot 2018-04-24 at 14 28 47](https://user-images.githubusercontent.com/1691849/39187106-a84390b2-47cc-11e8-8aff-50fd946871c7.png)
![screen shot 2018-04-24 at 14 28 55](https://user-images.githubusercontent.com/1691849/39187108-a85ee4b6-47cc-11e8-80c7-1a9aa4c26e59.png)
![screen shot 2018-04-24 at 14 29 04](https://user-images.githubusercontent.com/1691849/39187109-a87c7972-47cc-11e8-803b-752831749d45.png)
![screen shot 2018-04-24 at 14 29 14](https://user-images.githubusercontent.com/1691849/39187110-a89e110e-47cc-11e8-9fa7-bc98f519deee.png)
![screen shot 2018-04-24 at 14 29 24](https://user-images.githubusercontent.com/1691849/39187112-a8d4a87c-47cc-11e8-8661-3c0a77b449a0.png)
![screen shot 2018-04-24 at 14 29 34](https://user-images.githubusercontent.com/1691849/39187113-a8f33a62-47cc-11e8-9972-392a12cf2c53.png)

- run node wot-server.js
- got the attached message

![screen shot 2018-04-24 at 14 33 06](https://user-images.githubusercontent.com/1691849/39187129-b1648d7c-47cc-11e8-81b3-4b92fcea3850.png)

**Comment by domguinard** [comment]
Hi Carlo. This is due to the version of Node you are using. The Pi code is means for Node 4.x and incompatible with versions > 4.x. The book suggests installing v4.4.2 but you can find newer 4 versions from: https://nodejs.org/en/download/releases/
Let us know if that works. Note that we are working on a new version of the code that should support recent versions but it isn't ready yet.
