### ISSUE TITLE
Typos in chapter 7 middle converter

### ISSUE THREAD

**Issue by consulthys** [webofthings/wot-book#3]
On lines [41](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part1-2-direct-gateway/middleware/converter.js#L41) and [46](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part1-2-direct-gateway/middleware/converter.js#L46) of `middleware/converter.js`, `res.result` should read `req.result`

Listing 7.10 in the book.

**Comment by domguinard** [comment]
Okay, cheers, corrected!
