### ISSUE TITLE
Small typos in simple-plug.js of chapter 7

### ISSUE THREAD

**Issue by consulthys** [webofthings/wot-book#4]
- On [line 52](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part3-cloud/simple-plug.js#L52), `suceeded` should read `succeeded`.
- On [line 54](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part3-cloud/simple-plug.js#L54), `live` should read `livenow` (same as on [line 60](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part3-cloud/simple-plug.js#L60))

**Comment by domguinard** [comment]
Thanks for that! Fixed, will push next!
