### ISSUE TITLE
setInterval vs setTimeout

### ISSUE THREAD

**Issue by consulthys** [webofthings/wot-book#5]
In the script called [`simple-plug.js`](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part3-cloud/simple-plug.js#L52) (chapter 7), it'd be better to call `setInterval()` instead of `setTimeout` on [line 18](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part3-cloud/simple-plug.js#L18), so that `updateProperties()` doesn't need to schedule a new timeout every time it is called. 

Then in the [closing logic](https://github.com/webofthings/wot-book/blob/master/chapter7-implementation/part3-cloud/simple-plug.js#L44), you could simply call `clearInterval()` to clean it up properly.

**Comment by domguinard** [comment]
Absolutely makes sense, thanks for that, corrected and pushed!
