### ISSUE TITLE
Maskup code - Chapter 2 in GitHub different that what's in the book

### ISSUE THREAD

**Issue by PeterNJackson** [webofthings/wot-book#6]
The code in GitHub is not the samw as in the book:

BOOK:
function prepareMessage(name, location, localTemp, piTemp) {
var diff = localTemp - piTemp;
var qualifier = ' > ';
if (diff < 0) {
qualifier = ' < ';
}
var result = name + '@' + location + qualifier + Math.abs(diff);
return result;
}

**Comment by domguinard** [comment]
Hi Peter,

Thanks for your remark, actually we are in the revision phase of the book so the code indeed differs from the last published MEAP. This will be resolved as the last version of the meap is published.

The version on Git is the one that will be published in the next MEAP release.
