### ISSUE TITLE
Swap bullets B/C in facebook.js

### ISSUE THREAD

**Issue by consulthys** [webofthings/wot-book#7]
On line 22 of [facebook.js](https://github.com/webofthings/wot-book/blob/master/chapter9-sharing/social-auth/providers/facebook.js#L22), bullet `#C` should read `#B`.
On line 25 of [facebook.js](https://github.com/webofthings/wot-book/blob/master/chapter9-sharing/social-auth/providers/facebook.js#L25), bullet `#B` should read `#C`.

**Comment by domguinard** [comment]
corrected, cheers!
